### ISSUE TITLE
Please add WorldEdit mod

### ISSUE THREAD

**Issue by codexp** [TheRealDeveloper999/mc-modpack-New-minecraft#1]
https://www.curseforge.com/minecraft/mc-mods/worldedit

it would be nice!

![image](https://user-images.githubusercontent.com/6502486/227780355-9b22b026-2d8c-446f-9455-3694540538df.png)

**Comment by TheRealDeveloper999** [comment]
oh hi! i think it could be usefull

**Comment by TheRealDeveloper999** [comment]
i've done it
4f30fa43ede6160206ec152f8f23f3ba91d33eb3
